# Generated by Django 2.1.5 on 2019-04-01 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='choicetext',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='regdate',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
